### ISSUE TITLE
README clarifications

### ISSUE THREAD

**Issue by palfvin** [rubysolo/qrio#1]
Sorry for creating an issue, but I wasn't sure how else to contact you.

After reading the positive review in http://joshuadavey.com/2011/06/13/qr-codes-in-ruby/, I was surprised:
- to see the README statement that "QRio is not functional"
- to get an "undefined method `text`" error running the example code

However, I was able to successfully:
- load/run the software
- get the text result with `.qr.text` rather than `.text` as shown in the README

Has the software progressed significantly since the README was last revised or are you just being conservative?  In any event, I suggest that at least the usage example be updated.

Finally, unless an alternative comes up in response to http://stackoverflow.com/questions/21211487/need-qr-decoder-i-can-deploy-with-rails-on-heroku, I'd at least be willing to turn this into a gem.

**Comment by rubysolo** [comment]
No worries -- it's fine to create an issue!

I've tweaked the wording a bit in the README to reflect my meaning.  What I meant by "not functional" was that it does not have all the functionality/reliability I would want in a QR decoder.  For example, I would like to be able to support decoding all of the test images from the ZXing test suite, support all the modes (see http://en.wikipedia.org/wiki/QR_code#Storage), not just ASCII (Binary/byte), etc.

I had been waiting to work more on this before "officially" releasing the gem, and then it didn't seem like there was much demand for it, so I haven't worked on it in quite a while.  However, it would be great if this could be useful to you and others, so I've gone ahead and pushed the gem to rubygems.org.  If you run into more issues, I'd be happy to work with you to improve Qrio.

**Comment by palfvin** [comment]
Thanks, Solomon.  I really appreciate you're work on this.
